spring.application.name=Spring_Security_JWT_Authentication
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/jwt_db
spring.datasource.username=postgres
spring.datasource.password=endy123$$&&